# Generated by Django 3.1.3 on 2020-12-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_student_social_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
