# Generated by Django 3.1.3 on 2020-12-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201225_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='normalized_surname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
