# Generated by Django 3.1.3 on 2021-01-09 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.student'),
        ),
    ]
