# Generated by Django 3.1.3 on 2021-01-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210112_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ccy', models.CharField(max_length=10)),
                ('base_ccy', models.CharField(max_length=10)),
                ('buy', models.FloatField()),
                ('sale', models.FloatField()),
            ],
        ),
    ]
